

version: "3"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: bhayron
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: users

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
